// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TouristSpot.Infrastructure;

#nullable disable

namespace TouristSpot.Infrastructure.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20250203085517_SeedTouristSpotsData")]
    partial class SeedTouristSpotsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TouristSpot.Domain.Entities.TouristSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("TouristSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Rio de Janeiro",
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Estátua gigante de Jesus Cristo, localizada no Rio de Janeiro.",
                            Localization = "Parque Nacional da Tijuca",
                            Name = "Cristo Redentor",
                            State = "RJ"
                        },
                        new
                        {
                            Id = 2,
                            City = "Foz do Iguaçu",
                            CreatedDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cataratas do Iguaçu, uma das maiores quedas d'água do mundo.",
                            Localization = "Parque Nacional do Iguaçu",
                            Name = "Iguazu Falls",
                            State = "PR"
                        },
                        new
                        {
                            Id = 3,
                            City = "Rio de Janeiro",
                            CreatedDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Praia mundialmente famosa no Rio de Janeiro.",
                            Localization = "Avenida Atlântica",
                            Name = "Copacabana Beach",
                            State = "RJ"
                        },
                        new
                        {
                            Id = 4,
                            City = "Rio de Janeiro",
                            CreatedDate = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Montanha famosa do Rio de Janeiro com vista panorâmica.",
                            Localization = "Urca",
                            Name = "Pão de Açúcar",
                            State = "RJ"
                        },
                        new
                        {
                            Id = 5,
                            City = "Manaus",
                            CreatedDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Floresta tropical famosa pela biodiversidade.",
                            Localization = "Amazônia",
                            Name = "Amazônia",
                            State = "AM"
                        },
                        new
                        {
                            Id = 6,
                            City = "Cuiabá",
                            CreatedDate = new DateTime(2022, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A maior área úmida do mundo, rica em fauna e flora.",
                            Localization = "Pantanal Mato-Grossense",
                            Name = "Pantanal",
                            State = "MT"
                        },
                        new
                        {
                            Id = 7,
                            City = "Salvador",
                            CreatedDate = new DateTime(2022, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Centro histórico de Salvador, conhecido por sua arquitetura colonial.",
                            Localization = "Centro Histórico",
                            Name = "Pelourinho",
                            State = "BA"
                        },
                        new
                        {
                            Id = 8,
                            City = "São Paulo",
                            CreatedDate = new DateTime(2022, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Catedral gótica imponente localizada em São Paulo.",
                            Localization = "Praça da Sé",
                            Name = "Catedral da Sé",
                            State = "SP"
                        },
                        new
                        {
                            Id = 9,
                            City = "Manaus",
                            CreatedDate = new DateTime(2022, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teatro histórico situado no coração de Manaus.",
                            Localization = "Centro de Manaus",
                            Name = "Teatro Amazonas",
                            State = "AM"
                        },
                        new
                        {
                            Id = 10,
                            City = "São Paulo",
                            CreatedDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mercado tradicional em São Paulo, com produtos típicos.",
                            Localization = "Rua da Cantareira",
                            Name = "Mercado Municipal",
                            State = "SP"
                        },
                        new
                        {
                            Id = 11,
                            City = "Rio de Janeiro",
                            CreatedDate = new DateTime(2022, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lagoa famosa no Rio de Janeiro, rodeada por montanhas.",
                            Localization = "Zona Sul",
                            Name = "Lagoa Rodrigo de Freitas",
                            State = "RJ"
                        },
                        new
                        {
                            Id = 12,
                            City = "Rio de Janeiro",
                            CreatedDate = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Museu de História Natural e Antropologia no Rio de Janeiro.",
                            Localization = "Quinta da Boa Vista",
                            Name = "Museu Nacional",
                            State = "RJ"
                        },
                        new
                        {
                            Id = 13,
                            City = "Ouro Preto",
                            CreatedDate = new DateTime(2022, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cidade histórica conhecida por sua arquitetura colonial.",
                            Localization = "Ouro Preto",
                            Name = "Centro Histórico de Ouro Preto",
                            State = "MG"
                        },
                        new
                        {
                            Id = 14,
                            City = "Camaçari",
                            CreatedDate = new DateTime(2022, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Praia paradisíaca e ponto de observação de tartarugas.",
                            Localization = "Costa do Sauípe",
                            Name = "Praia do Forte",
                            State = "BA"
                        },
                        new
                        {
                            Id = 15,
                            City = "Itatiaia",
                            CreatedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reserva natural em Penedo, com cachoeiras e trilhas.",
                            Localization = "Alambari",
                            Name = "Serrinha do Alambari",
                            State = "RJ"
                        },
                        new
                        {
                            Id = 16,
                            City = "Ceará",
                            CreatedDate = new DateTime(2022, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Área de conservação no Ceará com belas praias e dunas.",
                            Localization = "Jericoacoara",
                            Name = "Parque Nacional de Jericoacoara",
                            State = "CE"
                        },
                        new
                        {
                            Id = 17,
                            City = "Foz do Iguaçu",
                            CreatedDate = new DateTime(2022, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Impressionante conjunto de quedas d'água na fronteira entre Brasil e Argentina.",
                            Localization = "Parque Nacional do Iguaçu",
                            Name = "Cataratas do Iguaçu",
                            State = "PR"
                        },
                        new
                        {
                            Id = 18,
                            City = "Cananéia",
                            CreatedDate = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ilha paradisíaca e parque natural no litoral paulista.",
                            Localization = "Ilha Cardoso",
                            Name = "Ilha do Cardoso",
                            State = "SP"
                        },
                        new
                        {
                            Id = 19,
                            City = "Chapada dos Veadeiros",
                            CreatedDate = new DateTime(2022, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vila no Parque Nacional da Chapada dos Veadeiros, famosa por suas trilhas.",
                            Localization = "Chapada dos Veadeiros",
                            Name = "São Jorge",
                            State = "GO"
                        },
                        new
                        {
                            Id = 20,
                            City = "Angra dos Reis",
                            CreatedDate = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ilha famosa por suas praias e biodiversidade.",
                            Localization = "Angra dos Reis",
                            Name = "Ilha Grande",
                            State = "RJ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
